spring:
  security:
    user:
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/granthaalaydb
    username: granthaalay
    password: granthaalay
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: true
    hibernate:
      ddl-auto: create-drop
